routes/web.php
<?php

use App\Http\Controllers\{
    DashboardController,
    KategoriController,
    LaporanController,
    ProdukController,
    mentahanController,
    PengeluaranController,
    PembelianController,
    PembelianDetailController,
    PenjualanController,
    PenjualanDetailController,
    SettingController,
    setengahJadiController,
    UserController,
    LaporanInventoryController,
    LaporanPengeluaranController,
};
use App\Models\setengahJadi;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::group(['middleware' => 'level:1'], function () {
        Route::get('/kategori/data', [KategoriController::class, 'data'])->name('kategori.data');
        Route::resource('/kategori', KategoriController::class);

        Route::get('/produk/data', [ProdukController::class, 'data'])->name('produk.data');
        Route::post('/produk/delete-selected', [ProdukController::class, 'deleteSelected'])->name('produk.delete_selected');
        Route::post('/produk/cetak-barcode', [ProdukController::class, 'cetakBarcode'])->name('produk.cetak_barcode');
        Route::resource('/produk', ProdukController::class);

        Route::get('/mentahan/data', [mentahanController::class, 'data'])->name('mentahan.data');
        Route::post('/mentahan/cetak-mentahan', [mentahanController::class, 'cetakmentahan'])->name('mentahan.cetak_mentahan');
        Route::resource('/mentahan', mentahanController::class);

        Route::get('/setengahJadi/data', [setengahJadiController::class, 'data'])->name('setengahJadi.data');
        Route::put('/setengahJadi/{id}/stok', [setengahJadiController::class, 'updateStok'])->name('setengahJadi.updateStok');
        Route::resource('/setengahJadi', setengahJadiController::class);

        Route::get('/pengeluaran/data', [PengeluaranController::class, 'data'])->name('pengeluaran.data');
        Route::resource('/pengeluaran', PengeluaranController::class);

        Route::get('/pembelian/data', [PembelianController::class, 'data'])->name('pembelian.data');
        Route::get('/pembelian/{id}/create', [PembelianController::class, 'create'])->name('pembelian.create');
        Route::resource('/pembelian', PembelianController::class)
            ->except('create');

        Route::get('/pembelian_detail/{id}/data', [PembelianDetailController::class, 'data'])->name('pembelian_detail.data');
        Route::get('/pembelian_detail/loadform/{diskon}/{total}', [PembelianDetailController::class, 'loadForm'])->name('pembelian_detail.load_form');
        Route::resource('/pembelian_detail', PembelianDetailController::class)
            ->except('create', 'show', 'edit');

        Route::get('/penjualan/data', [PenjualanController::class, 'data'])->name('penjualan.data');
        Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');
        Route::get('/penjualan/{id}', [PenjualanController::class, 'show'])->name('penjualan.show');
        Route::delete('/penjualan/{id}', [PenjualanController::class, 'destroy'])->name('penjualan.destroy');
    });

    Route::group(['middleware' => 'level:1,3'], function () {
        Route::get('/transaksi/baru', [PenjualanController::class, 'create'])->name('transaksi.baru');
        Route::post('/transaksi/simpan', [PenjualanController::class, 'store'])->name('transaksi.simpan');
        Route::get('/transaksi/selesai', [PenjualanController::class, 'selesai'])->name('transaksi.selesai');
        Route::get('/transaksi/nota-kecil', [PenjualanController::class, 'notaKecil'])->name('transaksi.nota_kecil');
        Route::get('/transaksi/nota-besar', [PenjualanController::class, 'notaBesar'])->name('transaksi.nota_besar');

        Route::get('/penjualan', [PenjualanController::class, 'index'])->name('penjualan.index');

        Route::get('/transaksi/{id}/data', [PenjualanDetailController::class, 'data'])->name('transaksi.data');
        Route::get('/transaksi/loadform/{diskon}/{total}/{diterima}', [PenjualanDetailController::class, 'loadForm'])->name('transaksi.load_form');
        Route::resource('/transaksi', PenjualanDetailController::class)
            ->except('create', 'show', 'edit');
    });

    Route::group(['middleware' => 'level:1,2'], function () {
        Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan.index');
        Route::get('/laporan/data/{awal}/{akhir}', [LaporanController::class, 'data'])->name('laporan.data');
        Route::get('/laporan/pdf/{awal}/{akhir}', [LaporanController::class, 'exportPDF'])->name('laporan.export_pdf');

        Route::get('/laporanInventory', [LaporanInventoryController::class, 'index'])->name('LaporanInventory.index');
        // Route::get('/laporanInventory',[LaporanInventoryController::class,'exportPDF'] )->name('LaporanInventory.exportpdf');

        Route::get('/laporanPengeluaran', [LaporanPengeluaranController::class, 'index'])->name('LaporanPengeluaran.index');

        Route::get('/user/data', [UserController::class, 'data'])->name('user.data');
        Route::resource('/user', UserController::class);

        Route::get('/setting', [SettingController::class, 'index'])->name('setting.index');
        Route::get('/setting/first', [SettingController::class, 'show'])->name('setting.show');
        Route::post('/setting', [SettingController::class, 'update'])->name('setting.update');
    });

    Route::group(['middleware' => 'level:1,2,3'], function () {
        Route::get('/profil', [UserController::class, 'profil'])->name('user.profil');
        Route::post('/profil', [UserController::class, 'updateProfil'])->name('user.update_profil');
    });
});

app/Models/SetengahJadi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class setengahJadi extends Model
{
    use HasFactory;

    protected $table = 'setengahJadi';
    protected $primaryKey = 'id_setengahJadi';
    protected $guarded = [];
}

app/Http/Controllers/SetengahJadiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\setengahJadi;
use App\Models\mentahan;

class SetengahJadiController extends Controller
{
    public function index()
    {
        $mentahan = mentahan::all()->pluck('nama_bahan', 'id_mentahan');

        return view('setengahJadi.index', compact('mentahan'));
    }

    public function data()
    {
        $setengahJadi = setengahJadi::leftJoin('mentahan', 'mentahan.id_mentahan', 'setengahJadi.id_mentahan')
            ->select('setengahJadi.*', 'nama_bahan')
            ->get();
        // $setengahJadi = setengahJadi::orderBy('id_setengahJadi', 'desc')->get();

        return datatables()
            ->of($setengahJadi)
            ->addIndexColumn()
            ->addColumn('aksi', function ($setengahJadi) {
                return '
                <div class="btn-group">
                    <button type="button" onclick="editForm(`' . route('setengahJadi.update', $setengahJadi->id_setengahJadi) . '`)" class="btn btn-xs btn-info btn-flat"><i class="fa fa-pencil"></i></button>
                    <button type="button" onclick="deleteData(`' . route('setengahJadi.destroy', $setengahJadi->id_setengahJadi) . '`)" class="btn btn-xs btn-danger btn-flat"><i class="fa fa-trash"></i></button>
                </div>
                ';
            })
            ->rawColumns(['aksi'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $setengahJadi = setengahJadi::create($request->all());

        return response()->json('Data berhasil disimpan', 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $setengahJadi = setengahJadi::find($id);

        return response()->json($setengahJadi);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // $setengahJadi = setengahJadi::find($id)->update($request->all());
        $setengahJadi = setengahJadi::find($id);

        $setengahJadi->nama = $request->nama;
        $setengahJadi->jumlah += $request->jumlah;
        $setengahJadi->update();

        $mentahan = mentahan::find($setengahJadi->id_mentahan);
        $mentahan->jumlah -= $request->mentah;
        $mentahan->update();

        return response()->json('Data berhasil disimpan', 200);
    }
    public function updateStok(Request $request, $id)
    {
        $setengahJadi = setengahJadi::find($id);

        $setengahJadi->nama = $request->nama;
        $setengahJadi->jumlah += $request->jumlah;
        $setengahJadi->update();

        $mentahan = Mentahan::find($setengahJadi->id_mentahan);
        $mentahan->jumlah -= $request->mentahan;
        $mentahan->update();

        return response()->json('Data berhasil disimpan', 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $setengahJadi = setengahJadi::find($id)->delete();

        return response(null, 204);
    }
}

resources/views/setengahJadi/form.blade.php
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="modal-form">
    <div class="modal-dialog modal-lg" role="document">
        <form action="" method="post" class="form-horizontal">
            @csrf
            @method('post')

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="nama" class="col-lg-2 col-lg-offset-1 control-label">Nama</label>
                        <div class="col-lg-6">
                            <input type="text" name="nama" id="nama" class="form-control" required autofocus>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="bahan" class="col-lg-2 col-lg-offset-1 control-label">Bahan</label>
                        <div class="col-lg-6">
                            <select name="id_mentahan" id="id_mentahan" class="form-control" required>
                                <option value="">Pilih Bahan Mentah</option>
                                @foreach ($mentahan as $key => $item)
                                <option value="{{ $key }}">{{ $item }}</option>
                                @endforeach
                            </select>
                            {{-- <input type="text" name="bahan" id="bahan" class="form-control" required> --}}
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="jumlah" class="col-lg-2 col-lg-offset-1 control-label">Jumlah Bahan Mentah</label>
                        <div class="col-lg-6">
                            <input type="number" name="mentah" id="mentah" rows="3" class="form-control"></input>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="jumlah" class="col-lg-2 col-lg-offset-1 control-label">Hasil Proses</label>
                        <div class="col-lg-6">
                            <input type="number" name="jumlah" id="jumlah" rows="3" class="form-control"></input>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-save"></i> Simpan</button>
                    <button type="button" class="btn btn-sm btn-flat btn-warning" data-dismiss="modal"><i
                            class="fa fa-arrow-circle-left"></i> Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/setengahJadi/form2.blade.php
<div class="modal fade" id="modal-form2" tabindex="-1" role="dialog" aria-labelledby="modal-form">
    <div class="modal-dialog modal-lg" role="document">
        <form action="" method="post" class="form-horizontal">
            @csrf
            @method('post')

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group row">
                        <label for="nama" class="col-lg-2 col-lg-offset-1 control-label">Nama</label>
                        <div class="col-lg-6">
                            <input type="text" name="nama" id="nama" class="form-control" required autofocus>
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="bahan" class="col-lg-2 col-lg-offset-1 control-label">Bahan</label>
                        <div class="col-lg-6">
                            <select name="id_mentahan" id="id_mentahan" class="form-control" required>
                                <option value="">Pilih Bahan Mentah</option>
                                @foreach ($mentahan as $key => $item)
                                <option value="{{ $key }}">{{ $item }}</option>
                                @endforeach
                            </select>
                            {{-- <input type="text" name="bahan" id="bahan" class="form-control" required> --}}
                            <span class="help-block with-errors"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm btn-flat btn-primary"><i class="fa fa-save"></i> Simpan</button>
                    <button type="button" class="btn btn-sm btn-flat btn-warning" data-dismiss="modal"><i
                            class="fa fa-arrow-circle-left"></i> Batal</button>
                </div>
            </div>
        </form>
    </div>
</div>

resources/views/setengahJadi/index.blade.php
@extends('layouts.master')

@section('title')
Bahan Setengah Jadi
@endsection

@section('breadcrumb')
@parent
<li class="active">Bahab Setengah Jadi</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <button onclick="addForm('{{ route('setengahJadi.store') }}')"
                    class="btn btn-success btn-xs btn-flat"><i class="fa fa-plus-circle"></i> Tambah</button>
            </div>
            <div class="box-body table-responsive">
                <table class="table table-stiped table-bordered">
                    <thead>
                        <th width="5%">No</th>
                        <th>Nama</th>
                        <th>Bahan</th>
                        <th>Jumlah</th>
                        <th width="15%"><i class="fa fa-cog"></i></th>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

@includeIf('setengahJadi.form')
@includeIf('setengahJadi.form2')
@endsection

@push('scripts')
<script>
    let table;

        $(function() {
            table = $('.table').DataTable({
                responsive: true,
                processing: true,
                serverSide: true,
                autoWidth: false,
                ajax: {
                    url: '{{ route('setengahJadi.data') }}',
                },
                columns: [{
                        data: 'DT_RowIndex',
                        searchable: false,
                        sortable: false
                    },
                    {
                        data: 'nama'
                    },
                    {
                        data: 'nama_bahan'
                    },
                    {
                        data: 'jumlah'
                    },
                    {
                        data: 'aksi',
                        searchable: false,
                        sortable: false
                    },
                ]
            });

            $('#modal-form').validator().on('submit', function(e) {
                if (!e.preventDefault()) {
                    $.post($('#modal-form form').attr('action'), $('#modal-form form').serialize())
                        .done((response) => {
                            $('#modal-form').modal('hide');
                            table.ajax.reload();
                        })
                        .fail((errors) => {
                            alert('Tidak dapat menyimpan data');
                            return;
                        });
                }
            });
            $('#modal-form2').validator().on('submit', function(e) {
                if (!e.preventDefault()) {
                    $.post($('#modal-form form').attr('action'), $('#modal-form2 form').serialize())
                        .done((response) => {
                            $('#modal-form2').modal('hide');
                            table.ajax.reload();
                        })
                        .fail((errors) => {
                            alert('Tidak dapat menyimpan data');
                            return;
                        });
                }
            });
        });

        function addForm(url) {
            $('#modal-form2').modal('show');
            $('#modal-form2 .modal-title').text('Tambah setengahJadi');

            $('#modal-form2 form')[0].reset();
            $('#modal-form2 form').attr('action', url);
            $('#modal-form2 [name=_method]').val('post');
            $('#modal-form2 [name=nama]').focus();
        }


        function stokForm(url) {
            $('#modal-form2').modal('show');
            $('#modal-form2 .modal-title').text('Tambah Stok');

            $('#modal-form2 form')[0].reset();
            $('#modal-form2 form').attr('action', url);
            $('#modal-form2 [name=_method]').val('put');
            $('#modal-form2 [name=nama]').focus();

            $.get(url)
                .done((response) => {
                    $('#modal-form2 [name=nama]').val(response.nama);
                    $('#modal-form2 [name=id_mentahan]').val(response.id_mentahan);
                    // $('#modal-form [name=jumlah]').val(response.jumlah);
                })
                .fail((errors) => {
                    alert('Tidak dapat menampilkan data');
                    return;
                });
        }
        function editForm(url) {
            $('#modal-form').modal('show');
            $('#modal-form .modal-title').text('Edit setengahJadi');

            $('#modal-form form')[0].reset();
            $('#modal-form form').attr('action', url);
            $('#modal-form [name=_method]').val('put');
            $('#modal-form [name=nama]').focus();

            $.get(url)
                .done((response) => {
                    $('#modal-form [name=nama]').val(response.nama);
                    $('#modal-form [name=id_mentahan]').val(response.id_mentahan);
                    // $('#modal-form [name=jumlah]').val(response.jumlah);
                })
                .fail((errors) => {
                    alert('Tidak dapat menampilkan data');
                    return;
                });
        }

        function deleteData(url) {
            if (confirm('Yakin ingin menghapus data terpilih?')) {
                $.post(url, {
                        '_token': $('[name=csrf-token]').attr('content'),
                        '_method': 'delete'
                    })
                    .done((response) => {
                        table.ajax.reload();
                    })
                    .fail((errors) => {
                        alert('Tidak dapat menghapus data');
                        return;
                    });
            }
        }
</script>
@endpush